### ISSUE TITLE
Example program panic

### ISSUE THREAD

**Issue by rw** [fmstephe/flib#2] opened 2016-09-02 08:04 UTC
When executing the example program, I consistently get a panic:

```
$ ./main -pqrw
runtime: writebarrierptr *0xc42088c000 = 0x2
fatal error: bad pointer in write barrier

runtime stack:
runtime.throw(0xd6503, 0x1c)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/panic.go:566 +0x95
runtime.writebarrierptr.func1()
        /usr/local/Cellar/go/1.7/libexec/src/runtime/mbarrier.go:151 +0xbd
runtime.systemstack(0xc42001e000)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
        /usr/local/Cellar/go/1.7/libexec/src/runtime/proc.go:1079

goroutine 20 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:252
fp=0xc4200266f0 sp=0xc4200266e8
runtime.writebarrierptr(0xc42088c000, 0x2)
        /usr/local/Cellar/go/1.7/libexec/src/runtime/mbarrier.go:152
+0x7b fp=0xc420026728 sp=0xc4200266f0
main.pqrwEnqueue(0x989680, 0xc420074000, 0x40, 0xc42001c120)
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/pqrw.go:43
+0x1ed fp=0xc4200267a0 sp=0xc420026728
runtime.goexit()
        /usr/local/Cellar/go/1.7/libexec/src/runtime/asm_amd64.s:2086
+0x1 fp=0xc4200267a8 sp=0xc4200267a0
created by main.pqrwTest
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/pqrw.go:28
+0xf1

goroutine 1 [chan receive]:
main.pqrwTest(0x989680, 0x2710, 0x40, 0x100000, 0x0)
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/pqrw.go:29
+0x114
main.main()
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/main.go:65
+0x290

goroutine 19 [runnable, locked to thread]:
main.pqrwDequeue(0x989680, 0xc420074000, 0x40, 0xc42001c120)
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/pqrw.go:57
+0xf5
created by main.pqrwTest
        <GOPATH>/src/github.com/fmstephe/flib/queues/spscq/perf_spscq/pqrw.go:27
+0xb1:
```

**Comment by fmstephe** [comment] 2016-09-04 11:58
Robert,

This panic is caused by the 'trick' of creating `unsafe.Pointer` values without allocating.

    unsafe.Pointer(uintptr(uint(t)))

This converts a simple integer `t` into a pointer. For each test run `t` starts at 0 and is incremented in the test loop to provide a predictable `unsafe.Pointer` that can be written to the queue.

Golang's garbage collector requires a write barrier for every write of a pointer value. In the problematic test we can see

    buffer[i] = unsafe.Pointer(uintptr(uint(t)))

which is writing a pointer into the buffer, invoking the write barrier.

As of 1.7 the write barrier checks that the pointer is within a valid range of pointer values

https://github.com/golang/go/blob/master/src/runtime/mbarrier.go#L148

specifically it checks whether the value is too small (`< minPhysPageSize`). Our low `t` values are caught by this check causing the panic we are seeing.

The solution to this immediate problem is to add an offset to `t` to push it up into a valid range. For this we have added a 

    func getValidPointer() uintptr {
            intVal := 0
            return uintptr(unsafe.Pointer(&intVal))
    }

function which creates a real pointer. We keep the same `t` values but offset them with the `uintptr` generated here.

This solves our mbarrier problem, but we still trip up on new safety checks within the 1.7 garbage collector. I'll write about that in another comment.

**Comment by fmstephe** [comment] 2016-09-04 12:21
After applying the fix described above we are seeing

    runtime: nelems=73 nfree=0 nalloc=73 previous allocCount=1 nfreed=65464
    fatal error: sweep increased allocation count

    runtime stack:
    runtime.throw(0xd750a, 0x20)
            /Users/fmstephe/golang/go/src/runtime/panic.go:566 +0x95
    runtime.(*mspan).sweep(0x18cbe0, 0x1100000000, 0xc400000001)
            /Users/fmstephe/golang/go/src/runtime/mgcsweep.go:287 +0x7ab
    runtime.sweepone(0x35386)
            /Users/fmstephe/golang/go/src/runtime/mgcsweep.go:112 +0xfe
    runtime.gosweepone.func1()
            /Users/fmstephe/golang/go/src/runtime/mgcsweep.go:124 +0x2b
    runtime.systemstack(0x147a00)
            /Users/fmstephe/golang/go/src/runtime/asm_amd64.s:298 +0x79
    runtime.mstart()
            /Users/fmstephe/golang/go/src/runtime/proc.go:1079

I haven't had time to do a detailed analysis of this problem. But it is clear that as of 1.7 Golang performs much more detailed checking, closing the scope of tricks you can play with unsafe.

By creating `unsafe.Pointer` values which point to memory which almost certainly hasn't been allocated

    func getValidPointer() uintptr {
            intVal := 0
            return uintptr(unsafe.Pointer(&intVal))
    }

combined with 

    unsafe.Pointer(uintptr(t) + ptr)

we get `unsafe.Pointer` values pointing into 'thin air'. This confuses the GC when it finds values which were never allocated.

The solution chosen here is to simply turn off the garbage collector.

This does not feel like a very good solution in the long term. The next step is to find an approach to performance testing which does not lean on the unsafe package.

**Closed** 2016-09-04 12:21 UTC
